version: '3.7'
services:
  sftp:
    image: t7tran/sftp:0.2.0
    ports:
    - "2222:2222"
    command:
    - foo:pass:1001
    environment:
      CHOWN_RECURSIVE: 'true'
    volumes:
    - upload:/home/foo/upload
volumes:
  upload:
    labels:
    - "app=sftp"
